#ifndef TENSORFORGE_DIALECT_TENSORFORGE_IR_TENSORFORGEDIALECT_H
#define TENSORFORGE_DIALECT_TENSORFORGE_IR_TENSORFORGEDIALECT_H

#include "mlir/IR/Dialect.h"

#include "TensorForge/Dialect/TensorForge/IR/TensorForgeDialect.h.inc"

#endif // TENSORFORGE_DIALECT_TENSORFORGE_IR_TENSORFORGEDIALECT_H
